name: Standard library build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    env:
      BUILD_CONFIG: Release
      BUILD_PATH: ./src/standard/Proton.Common.csproj

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          source-url: https://nuget.pkg.github.com/gpproton/index.json
          dotnet-version: |
            7.0.x
            8.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore
        run: dotnet restore $BUILD_PATH

      - name: Build
        run: dotnet build --no-restore $BUILD_PATH -c $BUILD_CONFIG

      - name: Test
        run: dotnet test $BUILD_PATH -c $BUILD_CONFIG --no-build

      - name: Pack
        run: dotnet pack --no-build $BUILD_PATH -c $BUILD_CONFIG -o ./artifacts

      - name: Add source
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet nuget update source --source "https://nuget.pkg.github.com/gpproton/index.json" github --username gpproton --password "$NUGET_AUTH_TOKEN" --store-password-in-clear-text

      - name: Publish
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet nuget push artifacts/*.nupkg --source "github" --api-key "$NUGET_AUTH_TOKEN"
