name: Standard library build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    env:
      BUILD_CONFIG: Release
      BUILD_PATH: ./src/standard/Proton.Common.csproj
      NUGET_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          source-url: ${{ env.NUGET_URL }}

      - name: Restore
        run: dotnet restore ${{ env.BUILD_PATH }}

      - name: Build
        run: dotnet build --no-restore ${{ env.BUILD_PATH }} -c ${{ env.BUILD_CONFIG }}

      - name: Test
        run: dotnet test ${{ env.BUILD_PATH }} -c ${{ env.BUILD_CONFIG }} --no-build

      - name: Pack
        run: dotnet pack --no-build ${{ env.BUILD_PATH }} -c ${{ env.BUILD_CONFIG }} -o ./artifacts

      - name: Update source and publish
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget update source --source ${{ env.NUGET_URL }} github --username gpproton --password ${{ env.NUGET_AUTH_TOKEN }} --store-password-in-clear-text
          dotnet nuget push artifacts/*.nupkg --source "github" --api-key ${{ env.NUGET_AUTH_TOKEN }}
