name: Standard library build

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    env:
      BUILD_CONFIG: Release
      BUILD_PATH: ./src/standard/Proton.Common.csproj

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          config-file: nuget.config
          source-url: https://nuget.pkg.github.com/gpproton/index.json
          dotnet-version: |
            7.0.x
            8.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore
        run: dotnet restore $BUILD_PATH

      - name: Build
        run: dotnet build --no-restore $BUILD_PATH -c $BUILD_CONFIG

      - name: Test
        run: dotnet test $BUILD_PATH -c $BUILD_CONFIG --no-build

      - name: Pack
        run: dotnet pack --no-build $BUILD_PATH -c $BUILD_CONFIG -o ./artifacts

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: preview
          nuget-api-key: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: nuget push artifacts/*.nupkg
