name: Standard library deployment

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    env:
      BUILD_CONFIG: Release
      NUGET_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - path: "./src/standard/Proton.Common.csproj"
          - path: "./src/http/Proton.Common.Http.csproj"
          - path: "./src/efcore/Proton.Common.EFCore.csproj"
          - path: "./src/aspnet/Proton.Common.AspNet.csproj"

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          source-url: ${{ env.NUGET_URL }}

      - name: Restore
        run: dotnet restore ${{ matrix.path }}

      - name: Build
        run: dotnet build --no-restore ${{ matrix.path }} -c ${{ env.BUILD_CONFIG }}

      - name: Test
        run: dotnet test ${{ matrix.path }} -c ${{ env.BUILD_CONFIG }} --no-build

      - name: Pack
        run: dotnet pack --no-build ${{ matrix.path }} -c ${{ env.BUILD_CONFIG }} -o ./artifacts

      - name: Update nuget source
        run: dotnet nuget update source -s ${{ env.NUGET_URL }} -u ${{ github.repository_owner }} -p ${{ env.NUGET_AUTH_TOKEN }} --store-password-in-clear-text github

      - name: Publish nuget package
        run: dotnet nuget push artifacts/*.nupkg -s ${{ env.NUGET_URL }} -k ${{ env.NUGET_AUTH_TOKEN }} --skip-duplicate
